### ISSUE TITLE
Changes to Guide

### ISSUE THREAD

**Issue by alapo** [aojeda/mobilab#8]
Noob Alert.

I'm not particularly refined with Ubuntu but I followed the guide and kept getting errors. Does anyone have any suggestions on things to try? I've posted a YouTube video showing the error [here](https://www.youtube.com/watch?v=o_zcT-XjiGs&feature=youtu.be)

**Comment by aojeda** [comment]
For whatever reason, your video gets stuck at second 1:30 so there may be other issues that I couldn't spot, anyway, I think that the problem is that to libraries to the system (step 3) you need to be root (just write `sudo` before `echo` and `ldconfig` commands). I have updated the [tutorial](https://github.com/aojeda/misc_scripts/blob/master/install_cudaica.md).

**Comment by aojeda** [comment]
For whatever reason, your video gets stuck at second 1:30 so there may be other issues that I couldn't spot, anyways, I think that the problem is that to libraries to the system (step 3) you need to be root (just write `sudo` before `echo` and `ldconfig` commands). I have updated the [tutorial](https://github.com/aojeda/misc_scripts/blob/master/install_cudaica.md).
